version: '3.3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=messages_app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "0.0.0.0:5050:80"

volumes:
  pgdata:
